function addIcono(id,src){document.getElementById("iconos").innerHTML+="<img id='"+id+"' href='javascript:void(0);' width='30px' onclick='document.getElementById(\"vB_Editor_001_textarea\").value+=\"[img]"+src+"[/img]\";' class='iconos' src='"+src+"'>";}
addIcono("ico1","https://www.dropbox.com/s/lrv3ryjjikjeg53/Emoji%20Smiley-01.png","http://goo.gl/yUBL5N");
addIcono("ico2","https://www.dropbox.com/s/1hs5cof2g95pp1b/Emoji%20Smiley-02.png","http://goo.gl/pN309h");
//addIcono("ico3","","http://goo.gl/PYIgdk");
//addIcono("ico4","","http://goo.gl/WlEfxR");
//addIcono("ico5","","http://goo.gl/BLMKzn");
//addIcono("ico6","","http://goo.gl/uZ3WBI");
addIcono("ico7","https://dl.dropboxusercontent.com/s/jes8bce01l4eod2/Emoji%20Smiley-07.png","http://goo.gl/5442st");
addIcono("ico8","https://dl.dropboxusercontent.com/s/wme5u1juyy3c6za/Emoji%20Smiley-08.png","http://goo.gl/d7F1Ml");
addIcono("ico9","https://dl.dropboxusercontent.com/s/e88dtjskfzvcez7/Emoji%20Smiley-09.png","http://goo.gl/FM1x1v");
addIcono("ico10","https://dl.dropboxusercontent.com/s/c32ruts7a2we7rk/Emoji%20Smiley-10.png","http://goo.gl/LFSmJ1");
addIcono("ico11","https://dl.dropboxusercontent.com/s/pzswonc03enesaj/Emoji%20Smiley-11.png","http://goo.gl/sfl34P");
addIcono("ico12","https://dl.dropboxusercontent.com/s/f3gwhhr1nt5arjx/Emoji%20Smiley-12.png","http://goo.gl/tBxAhD");
addIcono("ico13","https://dl.dropboxusercontent.com/s/cgeyjmtbxn19j9g/Emoji%20Smiley-13.png","http://goo.gl/8mk5XS");
addIcono("ico14","https://dl.dropboxusercontent.com/s/3ldjzl6sd1orhpq/Emoji%20Smiley-14.png","http://goo.gl/yjQKnE");
addIcono("ico15","https://dl.dropboxusercontent.com/s/mbca7qluof6u9cp/Emoji%20Smiley-15.png","http://goo.gl/EJxQhm");
addIcono("ico16","https://dl.dropboxusercontent.com/s/jlihfqaolcdux4k/Emoji%20Smiley-16.png","http://goo.gl/IKzm9I");
addIcono("ico17","https://dl.dropboxusercontent.com/s/wmybqyunexmq61b/Emoji%20Smiley-17.png","http://goo.gl/YQcmpF");
addIcono("ico18","https://dl.dropboxusercontent.com/s/uonxnq2577ij06l/Emoji%20Smiley-18.png","http://goo.gl/uJ0j7W");
addIcono("ico19","https://dl.dropboxusercontent.com/s/90pci29tpzcsh2g/Emoji%20Smiley-19.png","http://goo.gl/CO0XiD");
addIcono("ico20","https://dl.dropboxusercontent.com/s/tbhvux9qnumb40r/Emoji%20Smiley-20.png","http://goo.gl/09SWh0");
addIcono("ico21","https://dl.dropboxusercontent.com/s/2ql86br56fbq00w/Emoji%20Smiley-21.png","http://goo.gl/Cf1N7U");
addIcono("ico22","https://dl.dropboxusercontent.com/s/cybalj4ku3lyei8/Emoji%20Smiley-22.png","http://goo.gl/WzxQ8h");
addIcono("ico23","https://dl.dropboxusercontent.com/s/6i1ng9r9vevz3zp/Emoji%20Smiley-23.png","http://goo.gl/0oWFU0");
addIcono("ico24","https://dl.dropbox.com/s/gyysgs6sji1o1wo/Emoji%20Smiley-24.png","http://goo.gl/3eqFwr");
addIcono("ico25","https://dl.dropboxusercontent.com/s/jrxyk0nm0fagkw0/Emoji%20Smiley-25.png","http://goo.gl/gxNqu4");
addIcono("ico26","https://dl.dropboxusercontent.com/s/7vbyg089sjsqovo/Emoji%20Smiley-26.png","http://goo.gl/MsIVuZ");
addIcono("ico27","https://dl.dropboxusercontent.com/s/ekil7oif2vikx14/Emoji%20Smiley-27.png","http://goo.gl/LH7qWg");
addIcono("ico28","https://dl.dropboxusercontent.com/s/at3aiuhkn13rl68/Emoji%20Smiley-28.png","http://goo.gl/PyiQZQ");
addIcono("ico29","https://dl.dropboxusercontent.com/s/mvwhkeowomnmehc/Emoji%20Smiley-29.png","http://goo.gl/wtfht4");
addIcono("ico30","https://dl.dropboxusercontent.com/s/4sbnas2vf68y38j/Emoji%20Smiley-30.png","http://goo.gl/qYrfSo");
addIcono("ico31","https://dl.dropboxusercontent.com/s/ksu9p4x90f1xqs5/Emoji%20Smiley-31.png","http://goo.gl/K8qGvj");
addIcono("ico32","https://dl.dropboxusercontent.com/s/grgb0y0de6twy3i/Emoji%20Smiley-32.png","http://goo.gl/At0OlU");
addIcono("ico33","https://dl.dropboxusercontent.com/s/jkz2nswxyqv92ir/Emoji%20Smiley-33.png","http://goo.gl/9wsdcS");
addIcono("ico34","https://dl.dropboxusercontent.com/s/fdvpjhrje3ei3t7/Emoji%20Smiley-34.png","http://goo.gl/rL54jv");
addIcono("ico35","https://dl.dropboxusercontent.com/s/winedc6t8kv8ub2/Emoji%20Smiley-35.png","http://goo.gl/J4wpZ3");
addIcono("ico36","https://dl.dropboxusercontent.com/s/o3zwjtnyaljzcpq/Emoji%20Smiley-36.png","http://goo.gl/PTT06E");
addIcono("ico37","https://dl.dropboxusercontent.com/s/zj45wxw5mqnwxpx/Emoji%20Smiley-37.png","http://goo.gl/QLfG43");
addIcono("ico38","https://dl.dropboxusercontent.com/s/dwfdv9ddze2bkv0/Emoji%20Smiley-38.png","http://goo.gl/zPXzwp");
addIcono("ico39","https://dl.dropboxusercontent.com/s/lj6fg6dhrm7458v/Emoji%20Smiley-39.png","http://goo.gl/8vEfVg");
addIcono("ico40","https://dl.dropboxusercontent.com/s/r3jrhquye8no7fd/Emoji%20Smiley-40.png","http://goo.gl/XHEd2I");
addIcono("ico41","https://dl.dropboxusercontent.com/s/0vrvd7ggxlba7xg/Emoji%20Smiley-41.png","http://goo.gl/LuhVox");
=======
       	function addIcono(id,drop,src){
   		document.getElementById("iconos").innerHTML+="<img id='"+id+"' href='javascript:void(0);' width='30px' onclick='document.getElementById(\"vB_Editor_001_textarea\").value+=\"[img]"+src+"[/img]\";' class='iconos' src='"+drop+"'>";
   	}
addIcono("ico1","https://dl.dropbox.com/s/lrv3ryjjikjeg53/Emoji%20Smiley-01.png","http://goo.gl/yUBL5N")
addIcono("ico2","https://dl.dropbox.com/s/1hs5cof2g95pp1b/Emoji%20Smiley-02.png","http://goo.gl/pN309h")
addIcono("ico3","https://dl.dropbox.com/s/vangqlxemcea8nd/Emoji%20Smiley-03.png","http://goo.gl/PYIgdk")
addIcono("ico4","https://dl.dropbox.com/s/20gfruk85u5bnos/Emoji%20Smiley-04.png","http://goo.gl/WlEfxR")
addIcono("ico5","https://dl.dropbox.com/s/1noxju8op8gr5sd/Emoji%20Smiley-05.png","http://goo.gl/BLMKzn")
addIcono("ico6","https://dl.dropbox.com/s/q2byqnb0dvbwfpf/Emoji%20Smiley-06.png","http://goo.gl/uZ3WBI")
>>>>>>> FETCH_HEAD
